version: '3.9'

services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - gcp-creds:/creds
      - .:/app
    working_dir: /code
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: